---
  - include: pre.yml
  - include: vim.yml
  - include: atom.yml
  - include: docker.yml
  - include: vagrant.yml
  - include: nodejs.yml
  - include: java.yml
  - include: scala.yml
  - include: intellij.yml